name: PR Bench Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  check_bench:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check PR body for bench
        run: |
          pr_body=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r .body)

          bench=$(git show -s $hash | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g')

          if [ -z "$bench" ] && ! echo "$pr_body" | grep -qi "No functional change."; then
              echo "No bench found and 'No functional change.' not found."
              gh pr comment ${{ github.event.pull_request.number }} -b "Hello there! 👋 \
              I noticed that your pull request doesn't meet our requirements for the 'Bench' or 'Non functional change' criteria. Here's some guidance to help you address this: \

              - If you're making a functional change, make sure to include the appropriate 'Bench' information in the pull request body. The format for the bench information should be: `Bench: [bench_number]`. \

              - If your change is non-functional, please include the phrase 'No functional change.' somewhere in the pull request body. \

              This helps us ensure the quality of our codebase and streamline the review process. \

              If you have any questions or need further assistance, don't hesitate to ask. Thanks for your contribution! 🙌" \
          fi