# This workflow will run clang-format and comment on the PR.
# Because of security reasons, it is crucial that this workflow
# executes no shell script nor runs make.

name: Format Check
on:
  pull_request_target:
    branches:
      - 'master'
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  Stockfish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: Ubuntu 20.04 GCC
            os: ubuntu-20.04
            shell: bash
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        id: clang-format
        continue-on-error: true
        with:
          clang-format-version: '17'
          exclude-regex: 'incbin'

      - name: Comment on PR
        if: steps.clang-format.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            clang-format 17.0.3 needs to be run on this PR.
            If you do not have clang-format installed, the maintainer will run it when merging.

