name: Stockfish
on:
  workflow_call:
jobs:
  Stockfish:
    name: ${{ matrix.sanitizers.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      CXXFLAGS: "-Werror"
    strategy:
      matrix:
        config:
          - name: Ubuntu 20.04 GCC
            os: ubuntu-20.04
            compiler: g++
            comp: gcc
            shell: bash {0}
          - name: Windows 2022 Mingw-w64 GCC x86_64
            os: windows-2022
            compiler: clang++
            comp: clang
            shell: msys2 {0}
            ext: .exe
        sanitizers:
          - name: Run with thread sanitizer
            make_option: sanitize=thread
            instrumented_option: sanitizer-thread
          - name: Run with UB sanitizer
            make_option: sanitize=undefined
            instrumented_option: sanitizer-undefined
          - name: Run with address sanitizer
            make_option: sanitize=address
            instrumented_option: sanitizer-undefined
          - name: Run under valgrind
            make_option: ""
            instrumented_option: valgrind
          - name: Run under valgrind-thread
            make_option: ""
            instrumented_option: valgrind-thread
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        if: runner.os == 'Windows' && matrix.sanitizers.name == 'Run with address sanitizer'
        with:
          fetch-depth: 0

      - name: Download required linux packages
        if: runner.os != 'Windows'
        run: |
          sudo apt update
          sudo apt install expect valgrind g++-multilib

      - name: Setup msys and install required packages
        if: runner.os == 'Windows' && matrix.sanitizers.name == 'Run with address sanitizer'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msys_sys }}
          install: mingw-w64-x86_64-clang make git

      - name: Download the used network from the fishtest framework
        run: make net

      - name: Check compiler
        run: $COMPILER -v

      - name: Test help target
        run: make help

      - name: Check git
        run: git --version

      # Sanitizers

      - name: ${{ matrix.sanitizers.name }}
        if: runner.os != 'Windows' || (runner.os == 'Windows' && matrix.sanitizers.name == 'Run with address sanitizer')
        run: |
          export CXXFLAGS="-O1 -fno-inline"
          make clean
          make -j2 ARCH=x86-64-modern COMP=$COMP ${{ matrix.sanitizers.make_option }} debug=yes optimize=no build > /dev/null
          ../tests/instrumented.sh --${{ matrix.sanitizers.instrumented_option }}
