# This workflow will run clang-format and comment on the PR.
# Because of security reasons, it is crucial that this workflow
# executes no shell script nor runs make.
# Read this before editing: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: clang-format check
on:
  pull_request_target:
    branches:
      - 'master'
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  Stockfish:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        id: clang-format
        continue-on-error: true
        with:
          clang-format-version: '17=17.0.3'
          exclude-regex: 'incbin'

      - name: Comment on PR
        if: steps.clang-format.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            clang-format needs to be run on this PR.
            If you don't have clang-format installed, the maintainer will handle it when merging.
            Version used: 17.0.3


