name: Stockfish
on:
  push:
    tags:        
      - '*' 
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
    types:
      - opened
      - edited
      - synchronize

jobs:
  Prerelease:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # returns null if no pre-release exists
      - name: Get Commit SHA of Latest Pre-release
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "COMMIT_SHA=$(jq -r 'map(select(.prerelease)) | first | .tag_name' <<< $(curl -s https://api.github.com/repos/${{ github.repository_owner }}/Stockfish/releases))" >> $GITHUB_ENV

      # delete old previous pre-release and tag
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: env.COMMIT_SHA != 'null'
        with:
          tag_name: ${{ env.COMMIT_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Check-Bench:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check PR body for bench
        run: |
          pr_body=$(gh pr view ${{ github.event.pull_request.number }} --json body -q . | jq -r .body)

          bench=$(echo "$pr_body" | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g')

          echo $bench

          if [[ -z "$bench" ]] && echo "$pr_body" | grep -qi "No functional change."; then
              gh pr comment ${{ github.event.pull_request.number }} -b \
              "Hello there! 👋

            I noticed that your pull request doesn't meet our requirements for the 'Bench' or 'Non functional change' criteria.

            Here's some guidance to help you address this:

            - If you're making a functional change, make sure to include the appropriate bench information in the pull request body.
              The format for the bench information should be: 'Bench: [bench_number]'.

            - If your change is non-functional, please include the phrase 'No functional change.' somewhere in the pull request body.

            If you have any questions or need further assistance, don't hesitate to ask. Thanks for your contribution! 🙌"
            exit 1
          fi

  Sanitizers:
    needs: Check-Bench
    uses: ./.github/workflows/stockfish_sanitizers.yml
  Tests:
    needs: Check-Bench
    uses: ./.github/workflows/stockfish_test.yml
  Compiles:
    needs: Check-Bench
    uses: ./.github/workflows/stockfish_compile_test.yml
  Binaries:
    needs: Check-Bench
    if: github.ref == 'refs/heads/master' || (startsWith(github.ref_name, 'sf_') && github.ref_type == 'tag')
    uses: ./.github/workflows/stockfish_binaries.yml
  ARM_Binaries:
    needs: Check-Bench
    if: github.ref == 'refs/heads/master' || (startsWith(github.ref_name, 'sf_') && github.ref_type == 'tag')
    uses: ./.github/workflows/stockfish_arm_binaries.yml
