name: Stockfish
on:
  push:
    tags:
      - "*"
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Binaries:
    uses: ./.github/workflows/matrix_config.yml
    with:
      matrix: ""
#   CompileTest:
#     uses: ./.github/workflows/matrix_config.yml
#     with:
#       matrix: ./.github/workflows/compile_test.yml
