name: Stockfish
on:
  push:
    tags:
      - "*"
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) )
          echo "::set-output name=matrix::$TASKS"
  Binaries:
    needs: [Matrix]
    uses: ./.github/workflows/binaries.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
  Compile-Test:
    needs: [Matrix]
    uses: ./.github/workflows/compile_test.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
