name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Stockfish"]
    types:
      - completed

jobs:
  Comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v6
        if: github.event.workflow_run.conclusion != 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            for (const pull_request of context.payload.workflow_run.pull_requests) {
              github.rest.issues.createComment({
                issue_number: pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for contributing!\nPlease fix the include errors in this PR.\nYou can find the errors in the CI run.'
              })
            }
