name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Stockfish"]
    types:
      - completed

jobs:
  Comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v6
        if: github.event.workflow_run.conclusion != 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  context.issue.number ,
              body: 'Please fix the include errors in this PR.\n\n You can find the errors in the CI run.'
            });