name: Stockfish
on:
  push:
    tags:        
      - '*' 
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Analyzers:
    uses: ./.github/workflows/stockfish_analyzers.yml
