name: Stockfish
on:
  push:
    tags:        
      - '*' 
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if tag exists
        run: |
          if git tag -l | grep -q stockfish-prerelease; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi
        id: check_tag

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        if: ${{ steps.check_tag.outputs.tag_exists == 'true' }}
        with:
          token: ${{ github.token }}
          tag: stockfish-prerelease
          assets: 'stockfish-*.tar'
    
  # Sanitizers:
  #   uses: ./.github/workflows/stockfish_sanitizers.yml
  # Tests:
  #   uses: ./.github/workflows/stockfish_test.yml
  # Compiles:
  #   uses: ./.github/workflows/stockfish_compile_test.yml
  Binaries:
    if: github.ref == 'refs/heads/master' || (startsWith(github.ref_name, 'sf_') && github.ref_type == 'tag')
    uses: ./.github/workflows/stockfish_binaries.yml
  # ARM_Binaries:
  #   if: github.ref == 'refs/heads/master' || (startsWith(github.ref_name, 'sf_') && github.ref_type == 'tag')
  #   uses: ./.github/workflows/stockfish_arm_binaries.yml
