# This workflow will run clang-format and comment on the PR.
# Because of security reasons, it is crucial that this workflow
# executes no shell script nor runs make.
# Read this before editing: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: Format Check
on:
  pull_request_target:
    branches:
      - 'master'
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  Stockfish:
    name: Ubuntu 20.04 GCC
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        id: clang-format
        continue-on-error: true
        with:
          clang-format-version: '17'
          exclude-regex: 'incbin'

      - name: Extract clang-format version
        run: |
          CLANG_FORMAT_VERSION="$(clang-format --version)"
          echo "CLANG_VER=$CLANG_FORMAT_VERSION" >> $GITHUB_ENV

      - name: Comment on PR
        if: steps.clang-format.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ env.CLANG_VER }} needs to be run on this PR.
            If you don't have clang-format installed, the maintainer will handle it when merging.


